backend:
  name: github
  repo: kjirou/learn-hugo-on-netlify
  branch: main

publish_mode: editorial_workflow

media_folder: "/static/external/posts"
public_folder: "/external/posts"

# NOTE: 参考記事 = https://blog.terrier.dev/blog/2018/20180404000000-netlifycms-slug/
slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
